services:
  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: payment_processing_system
      POSTGRES_PASSWORD: payment_processing_system
      POSTGRES_DB: payment_processing_system
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      - NODE_ENV=development
    command: |
      /bin/sh -c "
      rm -f tmp/pids/server.pid &&
      until pg_isready -h db -p 5432 -U payment_processing_system; do sleep 1; done &&
      bundle exec rails db:create &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bundle exec rails s -b '0.0.0.0'
      "
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: